dist: xenial
language: python

python:
        - 3.7

services:
        - mysql

before_install:
        - mysql -u root -e "CREATE USER 'mm'@'localhost' IDENTIFIED BY 'password';"
        - mysql -u root -e "CREATE USER 'mm'@'%' IDENTIFIED BY 'password';"
        - mysql -u root -e "GRANT ALL ON *.* TO 'mm'@'localhost';"
        - mysql -u root -e "GRANT ALL ON *.* TO 'mm'@'%';"
        - mysql -u root -e "CREATE DATABASE moviemanager;"

install:
        - cd server
        - pip install -r requirements.txt
        - python3 manage.py makemigrations
        - python3 manage.py migrate
        - python3 manage.py test
