# Generated by Django 2.2 on 2019-04-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.SmallIntegerField()),
                ('avg_rating', models.SmallIntegerField()),
                ('plot', models.CharField(max_length=255)),
                ('poster_url', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('watched', models.ManyToManyField(to='moviemanager.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemanager.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemanager.User')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('movies', models.ManyToManyField(to='moviemanager.Movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemanager.User')),
            ],
        ),
    ]
